### ISSUE TITLE
Add custom 404 or somehow redirect all URLs to root

### ISSUE THREAD

**Issue by itsmartin** [OvercastNetwork/oc.tc#5]
Would be good to catch all incoming links and direct them to the same info. Seems like it's possible to do custom 404 pages on github so that is probably the simplest way.

**Comment by ehhthing** [comment]
Add a 404.html that has a meta refresh tag to send them to https://oc.tc

**Comment by TheMolkaPL** [comment]
This would help -> https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by Electroid** [comment]
Done.
